// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package repository

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO ` + "`" + `users` + "`" + ` (
  ` + "`" + `id` + "`" + `,
  ` + "`" + `username` + "`" + `,
  ` + "`" + `email` + "`" + `,
  ` + "`" + `role` + "`" + `,
  ` + "`" + `status` + "`" + `,
  ` + "`" + `last_login_at` + "`" + `
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?,
  ?
)
`

type CreateUserParams struct {
	ID          string       `json:"id"`
	Username    string       `json:"username"`
	Email       string       `json:"email"`
	Role        UsersRole    `json:"role"`
	Status      UsersStatus  `json:"status"`
	LastLoginAt sql.NullTime `json:"last_login_at"`
}

// ユーザーを作成する
func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error {
	_, err := db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.Status,
		arg.LastLoginAt,
	)
	return err
}
